CREATE DATABASE clinic;

CREATE TABLE patients (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  date_of_birth DATE
);

CREATE TABLE medical_histories (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP NOT NULL,
  patient_id INT NOT NULL,
  status VARCHAR(255) NOT NULL,
  FOREIGN KEY (patient_id) REFERENCES patients (id)
);

CREATE TABLE treatments (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE invoices (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  payed_at TIMESTAMP NOT NULL,
  medical_history_id INT NOT NULL,
  FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id)
);

CREATE TABLE invoice_items (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_price DECIMAL NOT NULL,
  quantity INT NOT NULL,
  total_price DECIMAL NOT NULL,
  invoice_id INT NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id),
  treatment_id INT NOT NULL,
  FOREIGN KEY (treatment_id) REFERENCES treatments(id)
);

CREATE TABLE treatments_history (
  treatment_id INT NOT NULL REFERENCES treatments(id),
  medical_history_id INT NOT NULL REFERENCES medical_histories(id),
);

CREATE INDEX patient_id_index ON medical_histories(patient_id);
CREATE INDEX medical_history_index ON invoices(medical_history_id);
CREATE INDEX invoice_id_index ON invoice_items(invoice_id);
CREATE INDEX treatment_id_index ON invoice_items(treatment_id);
CREATE INDEX treat_id_index ON treatments_history(treatment_id);
CREATE INDEX med_history_index ON treatments_history(medical_history_id);
